### ISSUE TITLE
TFS issue modification error for external email account

### ISSUE THREAD

**Issue by danseo-reisys** [microsoft/mail2bug#123]
Hello,
New TFS issue gets created fine when our client sends an email to our TFS service email address.
but anytime our client replies to the email thread, this mail2bug shows following error and does not modify existing TFS issue.
Anytime someone in our email group replies, TFS issue gets updated fine.    This behavior persists for all external client email address. 

Can you please make some recommendation?  

2022-01-06 11:50:56,913 [3] INFO  TfsEmailService.MessageProcessingStrategies.SimpleBugStrategy [(null)] - Modifying work item 191706 subject: RE: EXTERNAL: test
2022-01-06 11:50:56,916 [3] INFO  TfsEmailService.MessageProcessingStrategies.NameResolver [(null)] - Resolving name for alias/name larsenp/Peter Larsen
2022-01-06 11:50:56,917 [3] WARN  TfsEmailService.MessageProcessingStrategies.SpecialValueResolver [(null)] - Name resolution failed for sender alias 'larsenp'. Returning display name.
2022-01-06 11:50:56,949 [3] WARN  TfsEmailService.WorkItemManagement.TFSWorkItemManager [(null)] - 'Peter Larsen' is an invalid value for Changed By. Trying to find approximate value.
2022-01-06 11:50:56,952 [3] INFO  TfsEmailService.WorkItemManagement.TFSWorkItemManager [(null)] - Approximate value is 
2022-01-06 11:50:57,217 [3] ERROR TfsEmailService.Mail2BugEngine [(null)] - Error processing message
Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Team Foundation Server administrator. ---> System.Web.Services.Protocols.SoapException: Object reference not set to an instance of an object.
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at TfsEmailService.WorkItemManagement.TFSWorkItemManager.ValidateAndSaveWorkItem(WorkItem workItem) in C:\gh\TfsEmailService\TfsEmailService\WorkItemManagement\TFSWorkItemManager.cs:line 414
   at TfsEmailService.WorkItemManagement.TFSWorkItemManager.ModifyWorkItem(Int32 workItemId, String comment, Dictionary`2 values) in C:\gh\TfsEmailService\TfsEmailService\WorkItemManagement\TFSWorkItemManager.cs:line 321
   at TfsEmailService.MessageProcessingStrategies.SimpleBugStrategy.UpdateWorkItem(IIncomingEmailMessage message, Int32 workItemId) in C:\gh\TfsEmailService\TfsEmailService\MessageProcessingStrategies\SimpleBugStrategy.cs:line 178
   at TfsEmailService.MessageProcessingStrategies.SimpleBugStrategy.ProcessInboxMessage(IIncomingEmailMessage message) in C:\gh\TfsEmailService\TfsEmailService\MessageProcessingStrategies\SimpleBugStrategy.cs:line 44
   at TfsEmailService.Mail2BugEngine.ProcessInboxInternal() in C:\gh\TfsEmailService\TfsEmailService\Mail2BugEngine.cs:line 90

**Comment by femadex-github-readonly** [comment]
what is alternative to TFS/mail2bug?  does Azure Devops come with mail 2 bug capability?

**Comment by davisjr** [comment]
Looks like it's not able to update the `Changed by` field since the person is not in your organization. Could you try dropping the default for `Changed by` in your config so that the updates are marked as done by the account running mail2bug instead of the sender.
