### ISSUE TITLE
Exception while initializing instance 'Builds'

### ISSUE THREAD

**Issue by mmkumaran** [Microsoft/mail2bug#40]
Hi,

I get below error during start up, any idea how to fix this? (exchange user name and password seems to correct)
2016-07-18 22:46:21,449 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'Builds' (Persistent? True)
2016-07-18 22:46:21,496 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2016-07-18 22:46:21,511 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\mail2bug.bin
2016-07-18 22:46:21,527 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (user1@exchange.com, DIR\user1, 853411762)
2016-07-18 22:46:27,559 [1] ERROR Mail2Bug.MainApp [(null)] - Exception while initializing instance 'Builds'
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.DirectoryServices.ResultPropertyValueCollection.get_Item(Int32 index)
   at Microsoft.Exchange.WebServices.Autodiscover.DirectoryHelper.GetScpUrlList(String domainName, String ldapPath, Int32& maxHops)
   at Microsoft.Exchange.WebServices.Autodiscover.DirectoryHelper.GetAutodiscoverScpUrlsForDomain(String domainName)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetAutodiscoverServiceUrls(String domainName, Int32& scpHostCount)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetAutodiscoverServiceHosts(String domainName, Int32& scpHostCount)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetSettings[TGetSettingsResponseCollection,TSettingName](List`1 identities, List`1 settings, Nullable`1 requestedVersion, GetSettingsMethod`2 getSettingsMethod, Func`1 getDomainMethod)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(List`1 smtpAddresses, List`1 settings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetSoapUserSettings(String smtpAddress, List`1 requestedSettings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Mail2Bug.Email.EWS.EWSConnectionManger.ConnectToEWS(Credentials credentials) in h:\Downloads\mail2bug-master\mail2bug-master\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 91
   at Mail2Bug.Email.EWS.EWSConnectionManger.GetConnection(Credentials credentials) in h:\Downloads\mail2bug-master\mail2bug-master\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 61
   at Mail2Bug.Email.MailboxManagerFactory.CreateMailboxManager(EmailSettings emailSettings) in h:\Downloads\mail2bug-master\mail2bug-master\Mail2Bug\Email\MailboxManagerFactory.cs:line 29
   at Mail2Bug.Mail2BugEngine..ctor(InstanceConfig configInstance, MailboxManagerFactory mailboxManagerFactory) in h:\Downloads\mail2bug-master\mail2bug-master\Mail2Bug\Mail2BugEngine.cs:line 31
   at Mail2Bug.MainApp.InitInstances(IEnumerable`1 configs) in h:\Downloads\mail2bug-master\mail2bug-master\Mail2Bug\Main.cs:line 214
2016-07-18 22:46:27,575 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 0 ---------------

Thanks
Muthu

**Comment by hershi** [comment]
This suggests that the login credentials are not working (unfortunately, EWS doesn't give any good error messages for that)
Try replacing the username DIR\user1 with the format user1@exchange.com - this often works better when authenticating against EWS.

**Comment by mmkumaran** [comment]
Thanks for your reply. tried user1@exchange.com format didn't work either :(
