### ISSUE TITLE
Index out of range - EWS issue

### ISSUE THREAD

**Issue by RabidCadaver** [Microsoft/mail2bug#46]
So I've been wrestling with setting it up for a couple of days here, and I'm pretty confident that it's something that has to do with it signing into EWS. 

Below is my log for the run. I've tried it with a couple of different methods (two different accounts) and have run the testconnectivity.microsoft.com ews test which turned out green (not all the way, so that's a thing.)

But I was just looking for a little confirmation that it was the road I needed to jump down. 

2016-08-22 16:07:37,476 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'LegacyDefect' (Persistent? True)
2016-08-22 16:07:37,532 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2016-08-22 16:07:37,539 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\password.bin
2016-08-22 16:07:37,546 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (xxx@yyy.com, xxx@yyy.com, 1761024201, False)
2016-08-22 16:07:38,073 [1] ERROR Mail2Bug.MainApp [(null)] - Exception while initializing instance 'LegacyDefect'
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.DirectoryServices.ResultPropertyValueCollection.get_Item(Int32 index)
   at Microsoft.Exchange.WebServices.Autodiscover.DirectoryHelper.GetScpUrlList(String domainName, String ldapPath, Int32& maxHops)
   at Microsoft.Exchange.WebServices.Autodiscover.DirectoryHelper.GetAutodiscoverScpUrlsForDomain(String domainName)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetAutodiscoverServiceUrls(String domainName, Int32& scpHostCount)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetAutodiscoverServiceHosts(String domainName, Int32& scpHostCount)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetSettings[TGetSettingsResponseCollection,TSettingName](List`1 identities, List`1 settings, Nullable`1 requestedVersion, GetSettingsMethod`2 getSettingsMethod, Func`1 getDomainMethod)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(List`1 smtpAddresses, List`1 settings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetSoapUserSettings(String smtpAddress, List`1 requestedSettings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Mail2Bug.Email.EWS.EWSConnectionManger.ConnectToEWS(Credentials credentials, Boolean useConversationGuidOnly) in C:\Mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 91
   at Mail2Bug.Email.EWS.EWSConnectionManger.GetConnection(Credentials credentials, Boolean useConversationGuidOnly) in C:\Mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 61
   at Mail2Bug.Email.MailboxManagerFactory.CreateMailboxManager(EmailSettings emailSettings) in C:\Mail2bug\Mail2Bug\Email\MailboxManagerFactory.cs:line 29
   at Mail2Bug.Mail2BugEngine..ctor(InstanceConfig configInstance, MailboxManagerFactory mailboxManagerFactory) in C:\Mail2bug\Mail2Bug\Mail2BugEngine.cs:line 31
   at Mail2Bug.PersistentInstanceRunner..ctor(InstanceConfig instanceConfig, MailboxManagerFactory mailboxManagerFactory) in C:\Mail2bug\Mail2Bug\InstanceRunner.cs:line 21
   at Mail2Bug.MainApp.InitInstances(IEnumerable`1 configs) in C:\Mail2bug\Mail2Bug\Main.cs:line 214
2016-08-22 16:07:38,091 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 0 ---------------
2016-08-22 16:07:39,095 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 1 ---------------

**Comment by RabidCadaver** [comment]
We did some further testing, me and the exchange admin. Looks like our auto discover is screwed up somewhere in EWS, and that's a whole nother kettle of fishes. 

I have the URL for it, so is there somewhere I missed where I can just specify the URL?

**Comment by gxclarke** [comment]
Not as the code is written. You would need to modify EWSConnectionManger.cs (sic).

**Comment by hershi** [comment]
To expand on @gxclarke 's point - my suggestion would be for you to hack a version of your own where you hard-code the URL in EWSConnectionManager.cs . If that indeed solves your problem, then we can discuss the best way to implement support for this in a proper way through the config.
