### ISSUE TITLE
Instances failed to initialize do not retry

### ISSUE THREAD

**Issue by vitru** [Microsoft/mail2bug#48]
If there is a failure in instance initialization, Mail2Bug doesn't retry to re-init an instance and keeps iterating without processing that instance. This causes delays for that instance.

As an example of a failure we had some issue with Exchange Autodiscover service. This instance processing was delayed until we ran through all iterations and restarted mail2bug.exe process.

2016-09-27 14:28:40,820 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (oesvcm2b@microsoft.com, oesvcm2b@microsoft.com, 531558670, False)
2016-09-27 14:28:43,813 [1] ERROR Mail2Bug.MainApp [(null)] - Exception while initializing instance 'Git2Bug'
Microsoft.Exchange.WebServices.Data.AutodiscoverLocalException: The Autodiscover service couldn't be located.
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings[TSettings](String emailAddress, List`1 redirectionEmailAddresses, Int32& currentHop)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetLegacyUserSettings[TSettings](String emailAddress)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings(String emailAddress, List`1 requestedSettings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Mail2Bug.Email.EWS.EWSConnectionManger.ConnectToEWS(Credentials credentials, Boolean useConversationGuidOnly) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 91
   at Mail2Bug.Email.EWS.EWSConnectionManger.GetConnection(Credentials credentials, Boolean useConversationGuidOnly) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 61
   at Mail2Bug.Email.MailboxManagerFactory.CreateMailboxManager(EmailSettings emailSettings) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\Email\MailboxManagerFactory.cs:line 29
   at Mail2Bug.Mail2BugEngine..ctor(InstanceConfig configInstance, MailboxManagerFactory mailboxManagerFactory) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\Mail2BugEngine.cs:line 31
   at Mail2Bug.PersistentInstanceRunner..ctor(InstanceConfig instanceConfig, MailboxManagerFactory mailboxManagerFactory) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\InstanceRunner.cs:line 21
   at Mail2Bug.MainApp.InitInstances(IEnumerable`1 configs) in D:\GitRepos\Mail2Bug\mail2bug\Mail2Bug\Main.cs:line 214

**Comment by hershi** [comment]
This decision was by design, because the scenario where one configuration failed to initialize due to a transient error is not very common. The other option would be to retry every iteration, but because of the slowness of initializing EWS connections, if there is an instance that fails consistently, it would lengthen each and every iteration by a lot.
If this is a common instance for you, I'd suggest reducing the number of iterations per run of Mail2Bug, so that the delay for transiently failing instances is reduced.
Alternatively, you can implement functionality to retry failed instances every X iterations (X coming from AppConfig) and I can review the PR - though given that I consider this to be an edge-case, I don't know that the effort and added complexity are worth it for you to implement it.
