### ISSUE TITLE
Error when running scheduled task

### ISSUE THREAD

**Issue by hugocontreras** [Microsoft/mail2bug#53]
I configured everything properly to the point where the test shows me that there were no errors. So when I submit an email to the assigned address, wait for the job to run, and it's successful. I then see in the logs:

2016-12-08 17:06:46,969 [1] ERROR Mail2Bug.MainApp [(null)] - Exception caught in main - aborting. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\system32\Resources'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Mail2Bug.MainApp.Main(String[] args) in C:\TFS\costartfs\Scm\mail2bug-master\Mail2Bug\Main.cs:line 36

Not sure where to go from here. Server has VS2013 & 2015, Also has all other requirements. Not sure where else to look.

**Comment by hershi** [comment]
Seems like you're running the scheduled task without setting the working directory for it. As a result, it's looking for the path you've put for the config flies directly under C:\Windows\system32
Ideally, you should set the working folder appropriately. The alternative is to use absolute paths, but I'd say it's not as clean
