### ISSUE TITLE
BUG - Access in TFS with 365 account that doesn`t have project level information and work item create permissions

### ISSUE THREAD

**Issue by mgolban** [Microsoft/mail2bug#56]
Hello,

For my project http://che-tfsblssapp1.brooks.com:8080/tfs/CCS, with the email account ccstestsw@outlook.com that is not in my TFS Team Project, it succeeds to create new WITs (Issue), because like that I have defined for my project. The service is proceding with 200 iteration and after that it stops.

Below is the error log:

D:\Service>Mail2Bug.exe
2017-02-06 10:59:48,344 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'CCS' (Persistent? True)
2017-02-06 10:59:48,366 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2017-02-06 10:59:48,374 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\password.bin
2017-02-06 10:59:48,382 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 10:59:50,864 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initializing WorkItemManager
2017-02-06 10:59:50,870 [1] INFO  Mail2Bug.MainApp [(null)] - Finished initialization of engine for instance 'CCS'
2017-02-06 10:59:50,876 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 0 ---------------
2017-02-06 10:59:50,882 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 10:59:50,888 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 10:59:51,358 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Adding message to client queue: Client ID 100; subject: Test Bug2mail
2017-02-06 10:59:51,366 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 10:59:51,375 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 10:59:51,383 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Found 1 messages for Instance CCS. Processing...
2017-02-06 10:59:51,389 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Processing message Test Bug2mail
2017-02-06 10:59:51,396 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Working in standard mode, using TFSWorkItemManager
2017-02-06 10:59:51,687 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Connecting to TFS http://che-tfsblssapp1.brooks.com:8080/tfs/CCS using Microsoft.TeamFoundation.Client.TfsClientCredentials credentials
2017-02-06 10:59:52,299 [8] WARN  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - TFS connection attempt failed.
 Exception: Microsoft.TeamFoundation.TeamFoundationServerUnauthorizedException: TF30063: You are not authorized to access che-tfsblssapp1.brooks.com\CCS.
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.EnsureTokenProvider(HttpWebResponse webResponse)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequest()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpRequestChannel.Request(TfsMessage message, TimeSpan timeout)
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpClientBase.Invoke(TfsClientOperation operation, Object[] parameters, TimeSpan timeout, Object[]& outputs)
   at Microsoft.TeamFoundation.Framework.Client.LocationWebService.Connect(Int32 connectOptions, Int32 lastChangeId, Int32 features)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.Connect(ConnectOptions connectOptions)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.EnsureConnected(ConnectOptions optionsNeeded)
   at Microsoft.TeamFoundation.Framework.Client.FrameworkServerDataProvider.EnsureAuthenticated()
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureAuthenticated()
   at Mail2Bug.WorkItemManagement.TFSWorkItemManager.ConnectToTfsCollection() in D:\Projects\Mail2Bug\Mail2Bug\WorkItemManagement\TFSWorkItemManager.cs:line 61
2017-02-06 10:59:52,360 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Connecting to TFS http://che-tfsblssapp1.brooks.com:8080/tfs/CCS using Microsoft.TeamFoundation.Client.TfsClientCredentials credentials
2017-02-06 10:59:53,359 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Successfully connected to TFS
2017-02-06 10:59:53,366 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Connected to TFS. Getting TFS WorkItemStore
2017-02-06 10:59:55,552 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Geting TFS Project
2017-02-06 10:59:55,569 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Initializing WorkItems Cache
2017-02-06 10:59:55,576 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Initializing work items cache
2017-02-06 10:59:57,338 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - 0 items retrieved by TFS cache query
2017-02-06 10:59:57,374 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initializing MessageProcessingStrategy
2017-02-06 10:59:57,388 [8] INFO  Mail2Bug.MessageProcessingStrategies.NameResolver [(null)] - Resolving name for alias/name Marius.Golban/Golban, Marius (Consultant)
2017-02-06 10:59:57,395 [8] INFO  Mail2Bug.MessageProcessingStrategies.SpecialValueResolver [(null)] - Alias 'Marius.Golban', resolved to Golban, Marius (Consultant)
2017-02-06 10:59:57,442 [8] WARN  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - 'Unassigned' is an invalid value for Assigned To. Trying to find approximate value.
2017-02-06 10:59:57,452 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Approximate value is
2017-02-06 10:59:57,461 [8] ERROR Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Exception caught while trying to set value of field 'Priority  Path'
Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionNotExistException: TF26027: A field definition Priority  Path in the work item type definition file does not exist. Add a definition for this field or remove the reference to the field and try again.
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldDefinitionCollection.get_Item(String name)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.FieldCollection.get_Item(String name)
   at Mail2Bug.WorkItemManagement.TFSWorkItemManager.TryApplyFieldValue(WorkItem workItem, String key, String value) in D:\Projects\Mail2Bug\Mail2Bug\WorkItemManagement\TFSWorkItemManager.cs:line 411
2017-02-06 10:59:57,472 [8] WARN  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - 'Unassigned' is an invalid value for Assigned To. Trying to find approximate value.
2017-02-06 10:59:57,478 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Approximate value is
2017-02-06 11:00:04,961 [8] INFO  Mail2Bug.MessageProcessingStrategies.SimpleBugStrategy [(null)] - Added new work item 22 for message with subject: Test Bug2mail (conversation index:01D2805731C101151F089A614AA1A5BDB613B53043E0)
2017-02-06 11:00:14,301 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Message 'Test Bug2mail' processed successfully, moving to next message
2017-02-06 11:00:15,516 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 1 ---------------
2017-02-06 11:00:15,527 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:15,538 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:15,714 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:15,725 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:16,736 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 2 ---------------
2017-02-06 11:00:16,746 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:16,756 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:16,933 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:16,940 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:17,947 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 3 ---------------
2017-02-06 11:00:17,952 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:17,956 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:18,138 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:18,148 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:19,165 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 4 ---------------
2017-02-06 11:00:19,177 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:19,191 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:19,407 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:19,427 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:20,440 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 5 ---------------
2017-02-06 11:00:20,450 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:20,462 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:20,648 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:20,659 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:21,680 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 6 ---------------
2017-02-06 11:00:21,692 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:21,701 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:21,885 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:21,897 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:22,910 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 7 ---------------
2017-02-06 11:00:22,929 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:22,943 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:23,119 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:23,131 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:24,143 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 8 ---------------
2017-02-06 11:00:24,154 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:24,166 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:24,346 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:24,358 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:25,370 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 9 ---------------
2017-02-06 11:00:25,383 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:25,395 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:25,584 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:25,597 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:26,609 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 10 ---------------
2017-02-06 11:00:26,621 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (ccstestsw@outlook.com, ccstestsw@outlook.com, 2038550685, False)
2017-02-06 11:00:26,633 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:27,082 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Adding message to client queue: Client ID 100; subject: RE: Test Bug2mail
2017-02-06 11:00:27,094 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-02-06 11:00:27,103 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'CCS'
2017-02-06 11:00:27,112 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Found 1 messages for Instance CCS. Processing...
2017-02-06 11:00:27,120 [10] INFO  Mail2Bug.Mail2BugEngine [(null)] - Processing message RE: Test Bug2mail
2017-02-06 11:00:27,130 [10] INFO  Mail2Bug.MessageProcessingStrategies.SimpleBugStrategy [(null)] - Modifying work item 22 subject: RE: Test Bug2mail
2017-02-06 11:00:27,135 [10] INFO  Mail2Bug.MessageProcessingStrategies.NameResolver [(null)] - Resolving name for alias/name ccstestsw/CCS Support Test
2017-02-06 11:00:27,139 [10] WARN  Mail2Bug.MessageProcessingStrategies.SpecialValueResolver [(null)] - Name resolution failed for sender alias 'ccstestsw'. Returning display name.
2017-02-06 11:00:27,313 [10] WARN  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - 'CCS Support Test' is an invalid value for Changed By. Trying to find approximate value.
2017-02-06 11:00:27,322 [10] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Approximate value is
2017-02-06 11:00:40,468 [10] ERROR Mail2Bug.Mail2BugEngine [(null)] - Error processing message
Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Team Foundation Server administrator. ---> System.Web.Services.Protocols.SoapException: Object reference not set to an instance of an object.
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.Update(String requestId, XmlElement package, XmlElement& result, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SendUpdatePackage(XmlElement package, XmlElement& result, Boolean bulk)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.SaveWorkItems(WorkItem[] workitems, Boolean bulk, SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save(SaveFlags saveFlags)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.Save()
   at Mail2Bug.WorkItemManagement.TFSWorkItemManager.ValidateAndSaveWorkItem(WorkItem workItem) in D:\Projects\Mail2Bug\Mail2Bug\WorkItemManagement\TFSWorkItemManager.cs:line 390
   at Mail2Bug.WorkItemManagement.TFSWorkItemManager.ModifyWorkItem(Int32 workItemId, String comment, Dictionary`2 values) in D:\Projects\Mail2Bug\Mail2Bug\WorkItemManagement\TFSWorkItemManager.cs:line 304
   at Mail2Bug.MessageProcessingStrategies.SimpleBugStrategy.UpdateWorkItem(IIncomingEmailMessage message, Int32 workItemId) in D:\Projects\Mail2Bug\Mail2Bug\MessageProcessingStrategies\SimpleBugStrategy.cs:line 150
   at Mail2Bug.MessageProcessingStrategies.SimpleBugStrategy.ProcessInboxMessage(IIncomingEmailMessage message) in D:\Projects\Mail2Bug\Mail2Bug\MessageProcessingStrategies\SimpleBugStrategy.cs:line 44
   at Mail2Bug.Mail2BugEngine.ProcessInboxInternal() in D:\Projects\Mail2Bug\Mail2Bug\Mail2BugEngine.cs:line 79

**Comment by hershi** [comment]
I can only venture a guess here, since the exception message doesn't call out which value was null - it seems like you're trying to set the value of "Changed By" when updating the item, and the value you're trying to assign to it as an empty string (possibly null string). I suspect that this is an invalid value, which causes the exception. Try disabling the update of "Changed By" and see if that solves the issue

Relevant excerpt from the log you shared:
2017-02-06 11:00:27,130 [10] INFO Mail2Bug.MessageProcessingStrategies.SimpleBugStrategy [(null)] - Modifying work item 22 subject: RE: Test Bug2mail
2017-02-06 11:00:27,135 [10] INFO Mail2Bug.MessageProcessingStrategies.NameResolver [(null)] - Resolving name for alias/name ccstestsw/CCS Support Test
2017-02-06 11:00:27,139 [10] WARN Mail2Bug.MessageProcessingStrategies.SpecialValueResolver [(null)] - Name resolution failed for sender alias 'ccstestsw'. Returning display name.
2017-02-06 11:00:27,313 [10] WARN Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - 'CCS Support Test' is an invalid value for Changed By. Trying to find approximate value.
2017-02-06 11:00:27,322 [10] INFO Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Approximate value is
2017-02-06 11:00:40,468 [10] ERROR Mail2Bug.Mail2BugEngine [(null)] - Error processing message
Microsoft.TeamFoundation.WorkItemTracking.Client.UnexpectedErrorException: There is a problem on the server. Contact your Team Foundation Server administrator. ---> System.Web.Services.Protocols.SoapException: Object reference not set to an instance of an object.
...

**Comment by hershi** [comment]
Closing for now, since it seems like an issue with configuration rather than the code. Please reopen if needed

**Comment by inayat68** [comment]
Hello,

For my TFS project https://htrx.visualstudio.com/ which is configured with an office365 email account *****@health*****.com. As I did all configuration settings in my Mail2bug App and it successfully reads and queue these emails to TFS but failed to connect to TFS account/server. 

Please advise where I am doing wrong? The password is also okay as it is reading the emails correctly from inbox and TFS is configured with same email account. 

Also advise about the path to set in <CollectionUri> tag. I tried following one by one but none of them worked:

- https://htrx.visualstudio.com/DefaultCollection/GuideMedApplication/
- https://htrx.visualstudio.com/GuideMedApplication/GuideMedApplication%20Team
- https://htrx.visualstudio.com/GuideMedApplication/GuideMedApplication Team
- https://htrx.visualstudio.com/GuideMedApplication/
- https://htrx.visualstudio.com/GuideMedApp/_home

Below is the error log and screen shot showing the error line selected:

E:\Inayat\TFSEmailConfiguration\mail2bug-master\Mail2Bug\Service>mail2bug.exe
2017-09-19 11:04:58,551 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'GuideMed' (Persistent? True)
2017-09-19 11:04:58,573 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2017-09-19 11:04:58,580 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\mail2bug.bin
2017-09-19 11:04:58,580 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (c-kmujtaba@healthtrackrx.com, c-kmujtaba@healthtrackrx.com, 151243584, False)
2017-09-19 11:05:24,747 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initializing WorkItemManager
2017-09-19 11:05:24,762 [1] INFO  Mail2Bug.MainApp [(null)] - Finished initialization of engine for instance 'GuideMed'
2017-09-19 11:05:24,762 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 0 ---------------
2017-09-19 11:05:24,762 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Processing inbox for connection (c-kmujtaba@healthtrackrx.com, c-kmujtaba@healthtrackrx.com, 151243584, False)
2017-09-19 11:05:24,779 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Processing inbox for RecipientsMailboxManagerRouter
2017-09-19 11:05:27,855 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Adding message to client queue: Client ID 100; subject: TFS - Test Issue 16
2017-09-19 11:05:27,855 [1] INFO  Mail2Bug.Email.EWS.RecipientsMailboxManagerRouter [(null)] - Finished processing inbox for RecipientsMailboxManagerRouter
2017-09-19 11:05:27,870 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Running for config instance 'GuideMed'
2017-09-19 11:05:27,870 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Found 1 messages for Instance GuideMed. Processing...
2017-09-19 11:05:27,870 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Processing message TFS - Test Issue 16
2017-09-19 11:05:27,888 [8] INFO  Mail2Bug.Mail2BugEngine [(null)] - Working in standard mode, using TFSWorkItemManager
2017-09-19 11:05:27,908 [8] INFO  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - Connecting to TFS https://htrx.visualstudio.com/GuideMedApp/_home using Microsoft.TeamFoundation.Client.TfsClientCredentials credentials
2017-09-19 11:05:31,549 [8] WARN  Mail2Bug.WorkItemManagement.TFSWorkItemManager [(null)] - TFS connection attempt failed.
 Exception: Microsoft.TeamFoundation.TeamFoundationServiceUnavailableException: TF31002: Unable to connect to this Team Foundation Server: https://htrx.visualstudio.com/GuideMedApp/_home.
Team Foundation Server Url: https://htrx.visualstudio.com/GuideMedApp/_home.

Possible reasons for failure include:
- The name, port number, or protocol for the Team Foundation Server is incorrect.
- The Team Foundation Server is offline.
- The password has expired or is incorrect.

Technical information (for administrator):
The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.TeamFoundation.Client.Channels.TfsHttpWebRequest.SendRequestAndGetResponse(HttpWebRequest webRequest, WebException& webException)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureProviderConnected()
   at Microsoft.TeamFoundation.Client.TfsConnection.EnsureAuthenticated()
   at Mail2Bug.WorkItemManagement.TFSWorkItemManager.ConnectToTfsCollection() in 
![tfs-issue](https://user-images.githubusercontent.com/32088460/30578454-7020b312-9d2d-11e7-8635-809c9e9ed371.png)

Thanks
--
Inayat Ur Rehman
