### ISSUE TITLE
(401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by mapar007** [Microsoft/mail2bug#70]
I am getting un authorised access. Can someone help? 

2017-06-01 14:27:23,237 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'STCI CUSTOMER DSAT' (Persistent? True)
2017-06-01 14:27:23,263 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2017-06-01 14:27:23,273 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\mail2bug.bin
2017-06-01 14:27:23,279 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (mapar@microsoft.com, mapar@microsoft.com, -485684100, False)
2017-06-01 14:27:44,463 [1] ERROR Mail2Bug.MainApp [(null)] - Exception while initializing instance 'STCI CUSTOMER DSAT'
Microsoft.Exchange.WebServices.Data.ServiceRequestException: The request failed. The remote server returned an error: (401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(HttpWebRequest request)
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(HttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.BindToFolder(FolderId folderId, PropertySet propertySet)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.BindToFolder[TFolder](FolderId folderId, PropertySet propertySet)
   at Microsoft.Exchange.WebServices.Data.Folder.Bind(ExchangeService service, WellKnownFolderName name)
   at Mail2Bug.Email.EWS.EWSConnectionManger.ConnectToEWS(Credentials credentials, Boolean useConversationGuidOnly) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 102
   at Mail2Bug.Email.EWS.EWSConnectionManger.GetConnection(Credentials credentials, Boolean useConversationGuidOnly) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 61
   at Mail2Bug.Email.MailboxManagerFactory.CreateMailboxManager(EmailSettings emailSettings) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\MailboxManagerFactory.cs:line 31
   at Mail2Bug.Mail2BugEngine..ctor(InstanceConfig configInstance, MailboxManagerFactory mailboxManagerFactory) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Mail2BugEngine.cs:line 31
   at Mail2Bug.PersistentInstanceRunner..ctor(InstanceConfig instanceConfig, MailboxManagerFactory mailboxManagerFactory) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\InstanceRunner.cs:line 21
   at Mail2Bug.MainApp.InitInstances(IEnumerable`1 configs) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Main.cs:line 214

**Comment by mapar007** [comment]
Resolved this.

**Comment by iopreda** [comment]
I am having this same issue - could you post how you resolved?
